services:
  - type: web
    name: web-restaurant
    runtime: docker
    env: docker
    build:
      dockerfile: Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: "workstation id=WebRestaurant12.mssql.somee.com;packet size=4096;user id=dieuuu;pwd=123456789;data source=WebRestaurant12.mssql.somee.com;persist security info=False;initial catalog=WebRestaurant12;TrustServerCertificate=True"
      - key: Jwt__Key
        value: "YourSuperSecretKey123!"
      - key: Jwt__Issuer
        value: "WebRestaurantIssuer"
      - key: Jwt__Audience
        value: "WebRestaurantAudience"
    port: 80